### PR TITLE
Updated namespaces for Pressbooks 3.0.

### PR DESCRIPTION
**Pull request by greatislander**
Hi @bdolor, we are releasing Pressbooks 3.0 on Wednesday which, among other things, changes some namespaces for consistency. This pull request updates Pressbooks Textbook for compatibility. Will keep you posted on our rollout timeframe so that we can best coordinate.

### CODE REVIEW

**Comment by bdolor** [comment]
I'm around this week. Will stand by. Leaving this PR open until then, in case more changes find their way in.

**Comment by bdolor** [comment]
@greatislander Have you been able to get PBT to work with PB 3.0? Even with the changes in this PR, something is not quite right. Will dig into it this afternoon if nothing leaps out at you.

**Comment by greatislander** [comment]
@bdolor There may be specific changes we made that I missed in terms of their impact on PBT. However I'm not familiar with all of PBT's functionality so it's hard for me to say.

**Comment by bdolor** [comment]
@greatislander  - can you please modify namespace values at:
https://github.com/BCcampus/pressbooks-textbook/blob/dev/themes-book/opentextbook/page-cover-top-block.php#L72
https://github.com/BCcampus/pressbooks-textbook/blob/dev/includes/pbt-rewrite.php#L77

**Comment by greatislander** [comment]
Fixed. Also found another.

**Comment by bdolor** [comment]
great. thanks — compounding the problems was the php_minimum variable which is addressed here: https://github.com/pressbooks/pressbooks/commit/4cfe7534593693320d9a40b4a31171a947f5773c I will merge this PR.

**Comment by greatislander** [comment]
@bdolor I am at last ready to roll out Pressbooks 3.0 to https://wordpress.org. Let me know when you can release this update so we can coordinate.

**Comment by bdolor** [comment]
okay, sure — are you wanting to go today, or sometime tomorrow?

**Comment by greatislander** [comment]
Aiming for midday today.

**Pull request merged**
