### PR TITLE
Remove all redistribution functionality from PBT.

### PR DESCRIPTION
**Pull request by greatislander**
Full redistribution capability will be available in Pressbooks >= 3.8.
After this PR, Pressbooks Textbook will enable redistribution by default
as per #67.

### CODE REVIEW

**Comment by greatislander** [comment]
@bdolor Can you test this PR against https://github.com/pressbooks/pressbooks/pull/461 before merging? In my testing all seems to be working as expected, but would appreciate your eyes before I merge my portion of this change. I defer to you in terms of documenting the move for PBT users (Settings > PB Textbook > Redistribute moved to Settings > Export, plus a network admin-level control for whether or not redistribution should be allowed which PBT will override if installed and active).

**Comment by bdolor** [comment]
I tested the PR against https://github.com/pressbooks/pressbooks/pull/461 and couldn't detect any major problems.
1. We need to put the redistribute tab back, and do one of two things: provide a link to the new options setting, or provide the same interface which modifies the new option value `share_latest_export_files`. (The framework of permitted activities for an OER has 5 R's — reuse, revise, remix, retain and **redistribute**. We'd like not to misrepresent the framework.)
2. I was expecting to see the settings for the new option in `Theme Options > Web Options`. Is there resistance to seeing it moved there? 
3. With this PR we lose the different coloured icons for WXR export. There was a red one for PB exports and a blue one for Vanilla WP exports. We'd like not to lose this visual distinction between file types.

**Comment by greatislander** [comment]
@bdolor Thanks for the feedback.

1. Will do—I think providing a link is best so that there is a canonical place to manage the option.
2. My thinking had been that since it had to do with the way export files are handled (as opposed to a theme option, which I have always seen as how the book is displayed) it made more sense to have it under exports. But I see the merits of your suggestion. @hughmcguire, thoughts?
3. Fixed in https://github.com/pressbooks/pressbooks/pull/461/commits/e50fd01703ca7e45e868d3dffe800843919e3073

**Comment by greatislander** [comment]
Also: I haven't fully documented all the code in the related Pressbooks PR but I will be doing so with full copyright/credit before merging. This is a feature we've wanted in core for a long time and you've done the lion's share of building it out, so I will most certainly be attributing all the functions I ported/modified to you and indicating modifications where relevant. Thanks again @bdolor!

**Comment by greatislander** [comment]
@bdolor Updated this PR with the restored Redistribute tab (linking to Export settings, which is our preferred location). Also https://github.com/pressbooks/pressbooks/pull/461 has been updated with attribution for all the functions that I adapted from PBT. Let me know how it looks.

**Comment by bdolor** [comment]
Thanks @greatislander — can we flesh out the placement of the settings in web options vs export options? I disagree with @hughmcguire assessment that it does not affect how the book displays. The functionality does not exist without changing how the book displays. This is adding visual elements (buttons) to the cover page of the book. This is similar to the option to display social media buttons (currently the only other web option in `Web Options`). Thoughts?

**Comment by greatislander** [comment]
Yes, it does affect how the book displays on the web. But I was thinking of other ways this option would change the functionality of a book— for example, I could see the benefit of making download links for various export files available via the Pressbooks API if this option was enabled for a book. In that case, we'd then be in a position where the option to make export files available would be situated in the Web Theme Options but would impact the results of an API call, and web books =/= the API. The conclusion I came to was that since this is an option that impacts the use and availability of *all* export formats (not just Web) it should be a top-level export setting. Does that make more sense?

**Comment by bdolor** [comment]
okay, but that logic is flawed because it's also the case that `Email me validation error reports on export` in Export Settings =/= API. The point being that putting `Share the latest Export Files` in Export Settings is not a necessary condition. While Web Options =/= the API, it is also true that Export Settings =/= the API. In either location, web or export settings, the database value to be checked by an API request is the same, so really the scope of this should be about predictability for the user. If a precedent has been set to put options in a place that affect the display of a book in web options, and we both agree that this change affects the display of the book, there is merit to the suggestion. 
Has separating out API options, been a consideration? I can see value in giving people control over what type of information is shared.

**Comment by greatislander** [comment]
My point wasn’t that Export settings is where API settings are located, but rather that file sharing isn't a theming issue—it's a file handling/access issue. If this setting (make latest exports publicly available) is going to have broader implications than just the web theme's appearance, then I don't feel that it should be in the web theme options (as a user, I would be surprised if a web interface setting changed the API output of the service I was using). By this same logic, the social media controls are in the right place, as they control the appearance of the web book and have no impact elsewhere.

In terms of user predictability, maybe Privacy settings might be better than Export settings. That's where the user controls whether or not the web book is publicly accessible, and it might also be a sensible place for them to control whether the other exports are publicly accessible. What are your thoughts on that?

**Comment by hughmcguire** [comment]
Hi @bdolor I'm not quite understanding your perspective here? 

From my view, it's clear that:
* Theme Options are for "ways to change how the book looks, in its various outputs"
* "Allow downloads of books" adds functionality, which is not tied to "how the book looks/is displayed" ... but rather provides the reader with the ability to get the book in different formats.
 ... OK you need to make sure that those downloads are visible (and styled correctly) ... 

An analogy from WP core would be "enable comments" ... this is not a theme option, but rather a user/site setting. Of course it impacts how the Theme "looks" (in that the theme has comments or doesn't) ... but is not a theme option per se, but rather a user setting. Similarly with the downloads -- its has am "impact" on how the theme looks, but "changing how the theme looks" is not its primary reason for being.

Again, this is pretty clear to me... so perhaps I am missing something? Is the issue that that the feature has till now lived inside PB Textbook theme options? ... and so existing users expect to see it there?

**Comment by bdolor** [comment]
Hi Hugh, 

Here's what we know: 
- Theme Options are for 'ways to change how the book looks, in its various outputs'. 
- We agree that this functionality changes how the book looks. 

It could end there, as far as I'm concerned.

Here are some further considerations (and a more accurate comparison):
- The primary purpose of adding social media buttons (currently in Web Options) is ***not*** to change how the book looks. The primary purpose of adding social media buttons is to be able to share a link to a social media account(s). A requirement of that functionality is to alter how the book looks, albeit in a minor way. It lives in Web Options.
- The primary purpose of allowing public downloading of books is to redistribute a book, publicly. A requirement of that functionality is to alter how the book looks, albeit in a minor way. It should also live in Web Options.

Both pieces of functionality add buttons to the book in order to carry out their primary purpose. Putting the controls for one theme-altering-functionality in one place and another theme-altering-functionality in another is harder to explain than putting them together, in the same place where they do pretty much the same thing.  

So, from that perspective it is very straight forward, it follows a precedent already set, and as a consequence is likely to be intuitive to the user. I think some interesting points have been raised, and I hear your reasons for wanting to put it in Export Options, but I disagree that it is the most logical place to put something that affects how the book looks. 

While I would like consensus on this, I suppose I could  settle for it not being a requirement. I intend to put this in Theme Options in PBT, so if PB would like to put it somewhere else that's okay by me. If that's the route you go, please remove the line of code in PB that deletes a Pressbooks Textbook Option https://github.com/pressbooks/pressbooks/pull/461/files#diff-1aa91a4fe53425bb06ce902ef9e604eeR135

**Comment by greatislander** [comment]
Okay, as per our discussion— https://github.com/pressbooks/pressbooks/pull/461 now locates the redistribution setting under **Settings &rarr; Sharing & Privacy** and, for ease of migration, uses the existing `pbt_redistribute_settings` option. And I’ve updated the copy in this PR to reflect that. Also I've given you full credit in the relevant docblocks in https://github.com/pressbooks/pressbooks/pull/461 (e.g. [this](https://github.com/pressbooks/pressbooks/blob/436ff8307fe842cf263246b67be6a48277ca0123/includes/pb-utility.php#L150-L157)). Let me know if this works for you, @bdolor.

**Comment by bdolor** [comment]
Okay @greatislander - I had to resolve some conflicts and revert a few option values that were leftovers from decisions about where the redistribute options should live. Since the conflicts were resolved on my machine, I'm closing this PR, though the changes made in this PR are represented here: https://github.com/BCcampus/pressbooks-textbook/commit/df98d54f9185bc30de3b86c709cf8ee1511b4071 

thanks!

**Pull request closed without merging**
