### PR TITLE
Separate superscript/subscript buttons and prepare for migration to Pressbooks

### PR DESCRIPTION
**Pull request by greatislander**
Hi @bdolor & co! As per https://github.com/pressbooks/pressbooks/issues/157, I am submitting this pull request which:

1. Separates the MCE Textbook Buttons plugin in `/symbionts` so we can selectively migrate the superscript/subscript buttons, the anchor button and the textbook block element buttons into Pressbooks core.
2. Conditionally unsets the new superscript/subscript button plugin when Textbook is installed on an instance of the forthcoming Pressbooks 2.5.2, which will include it. Please let me know if you'd like me to make any changes to this prior to merge.

### CODE REVIEW

**Comment by bdolor** [comment]
Looks good @greatislander — though, I can't make the claim that I authored them. You should put your name on them. 
- https://github.com/BCcampus/pressbooks-textbook/pull/31/files#diff-50b7df5a32b7c1f743c173745d58f544R15
- https://github.com/BCcampus/pressbooks-textbook/pull/31/files#diff-eb2b8a1d9a7c6df044f85252d0705632R15

**Comment by greatislander** [comment]
🍻 Okay, will do.

**Comment by greatislander** [comment]
Hi @bdolor, updated the credits. Should be ready for you to merge.

**Comment by bdolor** [comment]
thanks @greatislander

**Comment by greatislander** [comment]
@bdolor Let me know when you release this update on wordpress.org and I will make the Pressbooks update live too.

**Comment by bdolor** [comment]
I will endeavor to release it within the hour. stand by...

**Comment by bdolor** [comment]
good to go — https://wordpress.org/plugins/pressbooks-textbook/changelog/

**Comment by greatislander** [comment]
Thanks!

**Pull request merged**
